// cuisines.ts
import { FaPizzaSlice, FaHamburger, FaFish } from 'react-icons/fa';
import { GiNoodles, GiSushis, GiMeat, GiChopsticks, GiChiliPepper, GiCroissant } from 'react-icons/gi';
import { MdOutlineRiceBowl } from 'react-icons/md';

export const cuisinesToFlags = [
    { name: "Italian", code: "IT" },
    { name: "Mexican", code: "MX" },
    { name: "Chinese", code: "CN" },
    { name: "Japanese", code: "JP" },
    { name: "Indian", code: "IN" },
    { name: "French", code: "FR" },
    { name: "Thai", code: "TH" },
    { name: "Greek", code: "GR" },
    { name: "Spanish", code: "ES" },
    { name: "American", code: "US" },
    { name: "Vietnamese", code: "VN" },
    { name: "Korean", code: "KR" },
    { name: "Brazilian", code: "BR" },
    { name: "Lebanese", code: "LB" },
    { name: "Turkish", code: "TR" },
    { name: "Moroccan", code: "MA" },
    { name: "German", code: "DE" },
    { name: "Russian", code: "RU" },
    { name: "British", code: "GB" },
    { name: "Swedish", code: "SE" },
    { name: "Australian", code: "AU" },
    { name: "Ethiopian", code: "ET" },
    { name: "Peruvian", code: "PE" },
    { name: "Argentinian", code: "AR" },
    { name: "Jamaican", code: "JM" },
    { name: "Filipino", code: "PH" },
    { name: "Indonesian", code: "ID" },
    { name: "Caribbean", code: "UM" }, // Placeholder regional code
    { name: "Israeli", code: "IL" },
];

// { name: "Italian", icon: <FaPizzaSlice /> },
// { name: "Mexican", icon: <FaTaco /> },
// { name: "Chinese", icon: <GiNoodles /> },
// { name: "Japanese", icon: <GiSushi /> },
// { name: "Indian", icon: <GiMeat /> },
// { name: "French", icon: <GiCroissant /> },
// { name: "Thai", icon: <GiChiliPepper /> },
// { name: "Greek", icon: <FaFish /> },
// { name: "Spanish", icon: <GiBurrito /> },
// { name: "Mediterranean", icon: <FaFish /> },
// { name: "American", icon: <FaHamburger /> },
// { name: "Vietnamese", icon: <MdOutlineRiceBowl /> },
// { name: "Korean", icon: <GiChopsticks /> },
// { name: "Brazilian", icon: <GiTurkeyLeg /> },
// { name: "Lebanese", icon: <GiChiliPepper /> },
// { name: "Turkish", icon: <FaFish /> },
// { name: "Moroccan", icon: <FaFish /> },
// { name: "German", icon: <GiMeat /> },
// { name: "Russian", icon: <FaFish /> },
// { name: "British", icon: <FaFish /> },
// { name: "Swedish", icon: <FaFish /> },
// { name: "Australian", icon: <FaFish /> },
// { name: "Ethiopian", icon: <FaFish /> },
// { name: "Peruvian", icon: <GiBurrito /> },
// { name: "Argentinian", icon: <GiMeat /> },
// { name: "Jamaican", icon: <GiChiliPepper /> },
// { name: "Filipino", icon: <MdOutlineRiceBowl /> },
// { name: "Indonesian", icon: <MdOutlineRiceBowl /> },
// { name: "Caribbean", icon: <GiBurrito /> },
// { name: "Israeli", icon: <GiChiliPepper /> },
