export const dishTypes = [
    "Appetizer",
    "Main Course",
    "Side Dish",
    "Soup",
    "Salad",
    "Dessert",
    "Snack",
    "Kids Meal",
    "Breakfast",
    "Brunch",
    "Lunch",
    "Dinner",
    "Beverage",
    "Cocktail",
    "Mocktail",
    "Smoothie",
    "Juice",
    "Sauce",
]
